## 數據預處理
* 遺漏值
* 類別變數轉換
* 特徵工程

In [1]:
import pandas as pd
from io import StringIO
import sys
#\下一行
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,,'''

df = pd.read_csv(StringIO(csv_data))
df

A     B    C    D
0   1.0   2.0  3.0  4.0
1   5.0   6.0  NaN  8.0
2  10.0  11.0  NaN  NaN

In [2]:
#確認每欄NA的數量
df.isnull().sum()

A    0
B    0
C    2
D    1
dtype: int64

In [3]:
#橫向刪除NA
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [4]:
#縱向刪除NA
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [5]:
#保留至少還有三個以上值得行
df.dropna(thresh=3)

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  NaN  8.0

In [6]:
#只踢掉D欄有NA的資料
df.dropna(subset=['D'])

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  NaN  8.0

### 填補NA --scikit-learn

In [7]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., nan, nan]])

In [8]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
#strategy 填補的方法 #median #most_frequent
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  3.,  8.],
       [10., 11.,  3.,  6.]])

### 處理類別變數
#### 第一種方法

In [30]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [10]:
#用字典轉換特徵
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}
df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [11]:
#反向轉換
inv_size_mapping = {v:k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

#### 第二種方法

In [12]:
import numpy as np

class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [13]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [14]:
#反向轉換
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

#### 第三種方法 scikit-learn LabelEncoder()

In [15]:
from sklearn.preprocessing import LabelEncoder

# Label encoding with sklearn's LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values) #fit_transform()先後呼叫fit & transform
y

array([1, 0, 1])

In [16]:
#反向轉換
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

### One hot encoding
#### scikit-learn

In [31]:
x = df[['color', 'size', 'price']].values
#color_le = LabelEncoder()
#x[:, 0] = color_le.fit_transform(x[:, 0])
x

array([['green', 'M', 10.1],
       ['red', 'L', 13.5],
       ['blue', 'XL', 15.3]], dtype=object)

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

ohe = ColumnTransformer([("ohe1", OneHotEncoder(),[0])], remainder="passthrough") 
#https://stackoverflow.com/questions/54345667/onehotencoder-categorical-features-depreciated-how-to-transform-specific-column
#https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html
ohe.fit_transform(x)

array([[0.0, 1.0, 0.0, 'M', 10.1],
       [0.0, 0.0, 1.0, 'L', 13.5],
       [1.0, 0.0, 0.0, 'XL', 15.3]], dtype=object)

In [19]:
from sklearn.compose import ColumnTransformer 
ct = ColumnTransformer([("Name_Of_Your_Step", OneHotEncoder(),[0])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
ct.fit_transform(X)   

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2